---
- name: setup filebeat
  hosts: servers_web
  become: yes

  vars:
    kibana_host: kibana
    elastic_host: elastic
  tasks:
  - name: install filebeat
    apt:
      deb: "https://mirror.yandex.ru/mirrors/elastic/7/pool/main/f/filebeat/filebeat-7.17.9-amd64.deb"

  - name: copy filebeat
    template:
      src: /home/xyden/Diplom/ansible-diplom/filebeat.j2
      dest: /etc/filebeat/filebeat.yml

  - name: daemon_reload
    systemd:
      daemon_reload: true


  - name: restart filebeat
    service:
      name: filebeat
      state: restarted
      enabled: yes

