---
- name: install zabbix server
  hosts: server_zabbix
  become: true
  
  vars:
    - password: zabbix

  tasks:
    - name: zabbix repo
      shell: wget https://repo.zabbix.com/zabbix/6.4/debian/pool/main/z/zabbix-release/zabbix-release_latest_6.4+debian12_all.deb
      args:
        chdir: /tmp

    - name: install zabbix
      shell: dpkg -i zabbix-release_latest_6.4+debian12_all.deb
      args:
        chdir: /tmp

    - name: update cache
      apt:
        update_cache: yes

    - name: install zabbix packages
      apt:
        name: 
          - apache2
          - postgresql
 #         - postgresql-contrib
          - python3-pexpect
          - python3-pip
          - python3-dev
          - python3-venv
          - python3-psycopg2
          - zabbix-server-pgsql
          - zabbix-frontend-php
          - php8.2-pgsql
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-agent 
        state: present

    - name: create user postgreSQL for zabbix
      expect:
        command: sudo -u postgres createuser --pwprompt zabbix
        responses:
          (?i).*(Enter password for new role)(.*):
            - '{{ password }}'
          (?i).*(Enter it again)(.*):
            - '{{ password }}'
  
    - name: create DB postgreSQL for zabbix
      shell:
        sudo -u postgres createdb -O zabbix zabbix
  
    - name: Импорт начальной схемы и данных
      shell: zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | sudo -u zabbix psql zabbix
  
    - name: Настройка DBPassword в конфигурационном файле Zabbix
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: "^DBPassword="
        line: "DBPassword=zabbix"
  
    - name: restart zabbix
      service:
        name: "{{ item }}"
        state: restarted
        enabled: yes
  
      loop:
        - zabbix-server
        - zabbix-agent
        - apache2
  